name:                distributors
version:             0.1.0.0
github:              "morphismtech/distributors"
license:             BSD-3-Clause
author:              "Eitan Chatav"
maintainer:          "eitan.chatav@gmail.com"
copyright:           "2023 Eitan Chatav"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/morphismtech/distributors#readme>

dependencies:
- base >= 4.7 && < 5
- adjunctions >= 4.4 && < 5
- bifunctors >= 5.6 && < 6
- bytestring >= 0.11 && < 1
- containers >= 0.6 && < 1
- contravariant >= 1.5 && < 2
- distributive >= 0.6 && < 1
- lens >= 5.2 && < 6
- mtl >= 2.3 && < 3
- profunctors >= 5.6 && < 6
- tagged >= 0.8 && < 1
- text >= 2 && < 3
- vector >= 0.13 && < 1
- witherable >= 0.4 && < 1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

default-extensions:
- AllowAmbiguousTypes
- Arrows
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFunctor
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- ImpredicativeTypes
- InstanceSigs
- KindSignatures
- LambdaCase
- MagicHash
- MonoLocalBinds
- OverloadedStrings
- QuantifiedConstraints
- RankNTypes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances
- UndecidableSuperClasses

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - distributors
      - hspec
