name: distributors
version: 0.2.0.1
github: "morphismtech/distributors"
license: BSD-3-Clause
author: "Eitan Chatav"
maintainer: "eitan.chatav@gmail.com"
copyright: "2025 Eitan Chatav"

extra-source-files:
- README.md
extra-doc-files:
- CHANGELOG.md


category: Profunctors, Optics, Parsing
synopsis: Unifying Parsers, Printers & Grammars
description:
  Distributors provides mathematically inspired abstractions
  for coders to write parsers that can also be inverted to printers.

dependencies:
- base >= 4.7 && < 5
- adjunctions >= 4.4 && < 5
- bifunctors >= 5.6 && < 6
- bytestring >= 0.11 && < 1
- containers >= 0.6 && < 1
- contravariant >= 1.5 && < 2
- distributive >= 0.6 && < 1
- lens >= 5.2 && < 6
- mtl >= 2.3 && < 3
- indexed-transformers >= 0.1.0.4 && < 1
- profunctors >= 5.6 && < 6
- tagged >= 0.8 && < 1
- template-haskell
- text >= 2 && < 3
- th-abstraction
- vector >= 0.13 && < 1
- witherable >= 0.4 && < 1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

default-extensions:
- AllowAmbiguousTypes
- Arrows
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- ImpredicativeTypes
- InstanceSigs
- LambdaCase
- MagicHash
- MonoLocalBinds
- OverloadedStrings
- QuantifiedConstraints
- RankNTypes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances
- UndecidableSuperClasses

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - distributors
      - hspec
